language: go

go:
  - 1.x

sudo: false

git:
  depth: 10

branches:
  only:
    - hugo

install:
  # Hugo - documentation
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - make hugo-build

deploy:
  - provider: pages
    target_branch: master
    local_dir: public
    edge: true
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}
    on:
      repo: SoCraTes-CA/socrates-fr.github.io
      branch: hugo
